-- 添加测试数据（数据共享模式）
-- 只添加候选人数据，使用NULL作为owner_id避免外键约束

-- 添加测试候选人数据（注意：owner_id 现在不重要了，因为是共享数据）
INSERT INTO resumes (
  id, 
  name, 
  email, 
  phone, 
  current_title, 
  current_company, 
  location, 
  years_of_experience, 
  expected_salary_min, 
  expected_salary_max, 
  skills, 
  education, 
  experience, 
  certifications, 
  languages, 
  status, 
  owner_id, 
  created_at, 
  updated_at
) VALUES 
  (
    '2b52fec8-8f63-41dc-acc4-af6e168e0cbc',
    '张三',
    'zhangsan@example.com',
    '13800138001',
    '全栈开发工程师',
    '深圳科技有限公司',
    '深圳',
    5,
    15000,
    25000,
    ARRAY['JavaScript', 'TypeScript', 'React', 'Node.js', 'Python', 'PostgreSQL'],
    '{"degree": "本科", "major": "计算机科学", "school": "深圳大学", "year": 2019}',
    '{"companies": [{"name": "深圳科技有限公司", "position": "全栈开发工程师", "duration": "2019-至今"}]}',
    '{"certs": ["AWS认证", "React开发者认证"]}',
    '{"languages": ["中文", "英文"]}',
    'active',
    NULL,
    NOW(),
    NOW()
  ),
  (
    '24bb3714-1be1-4382-8e7e-e60b11362cec',
    '李四',
    'lisi@example.com',
    '13800138002',
    '前端开发工程师',
    '广州互联网公司',
    '广州',
    3,
    12000,
    18000,
    ARRAY['JavaScript', 'Vue.js', 'React', 'CSS', 'HTML', 'Webpack'],
    '{"degree": "本科", "major": "软件工程", "school": "中山大学", "year": 2021}',
    '{"companies": [{"name": "广州互联网公司", "position": "前端开发工程师", "duration": "2021-至今"}]}',
    '{"certs": ["Vue.js认证"]}',
    '{"languages": ["中文", "英文"]}',
    'active',
    NULL,
    NOW(),
    NOW()
  ),
  (
    'f064ad0d-d512-4881-a4de-478ebc4f2dac',
    '王五',
    'wangwu@example.com',
    '13800138003',
    'Python后端开发工程师',
    '北京大数据公司',
    '北京',
    4,
    18000,
    28000,
    ARRAY['Python', 'Django', 'Flask', 'PostgreSQL', 'Redis', 'Docker'],
    '{"degree": "硕士", "major": "计算机技术", "school": "清华大学", "year": 2020}',
    '{"companies": [{"name": "北京大数据公司", "position": "Python后端开发工程师", "duration": "2020-至今"}]}',
    '{"certs": ["Python认证", "Docker认证"]}',
    '{"languages": ["中文", "英文"]}',
    'active',
    NULL,
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING; 